# Generated by Django 4.1.7 on 2023-09-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complain",
            old_name="address",
            new_name="subject",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="address",
            new_name="subject",
        ),
        migrations.AddField(
            model_name="roomuser",
            name="has_a_hostel",
            field=models.BooleanField(
                default=False, verbose_name="Do you own a hostel?"
            ),
        ),
    ]
