# Generated by Django 4.1.7 on 2023-07-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
        ('atlass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
            preserve_default=False,
        ),
    ]
