# Generated by Django 4.1.7 on 2023-06-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(default='Male', help_text='Male/Female', max_length=10),
            preserve_default=False,
        ),
    ]
