# Generated by Django 4.1.7 on 2023-09-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlass", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(help_text="YYYY-MM-DD"),
        ),
    ]
