# Generated by Django 4.1.7 on 2023-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlass', '0002_remove_booking_email_booking_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.CharField(max_length=20),
        ),
    ]
