# Generated by Django 4.1.7 on 2023-06-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlass', '0002_remove_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1.9, max_digits=1000000000),
            preserve_default=False,
        ),
    ]
