# Generated by Django 4.1.7 on 2023-06-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlass', '0003_alter_booking_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receit_number',
            field=models.CharField(default='0001', max_length=10),
            preserve_default=False,
        ),
    ]
