# Generated by Django 4.1.7 on 2023-06-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_alter_hostelimages_options'),
        ('atlass', '0004_alter_account_balance_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='booking_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
