# Generated by Django 4.1.7 on 2023-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='max_guests',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_bedrooms',
            field=models.PositiveIntegerField(),
        ),
    ]
