# Generated by Django 4.1.7 on 2023-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_apartment_max_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=None, upload_to='unarcom/properties/images'),
        ),
    ]
