# Generated by Django 4.1.7 on 2023-05-26 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
