# Generated by Django 4.1.7 on 2023-05-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
