# Generated by Django 4.1.7 on 2023-05-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='account_no',
        ),
    ]
