# Generated by Django 4.1.7 on 2023-06-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
