# Generated by Django 4.1.7 on 2023-05-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelImages',
        ),
    ]
