# Generated by Django 4.1.7 on 2023-04-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='slug',
        ),
    ]
