# Generated by Django 5.0.3 on 2025-08-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='hostels/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='occupant_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], db_index=True, default='mixed', max_length=10),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['occupant_gender'], name='hostels_roo_occupan_c650da_idx'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostels.hostel'),
        ),
        migrations.AddIndex(
            model_name='hostelimage',
            index=models.Index(fields=['hostel', 'order'], name='hostels_hos_hostel__8b203a_idx'),
        ),
    ]
