# Generated by Django 4.1.7 on 2023-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='hostel',
            name='category',
            field=models.IntegerField(choices=[(1, 'GHS500-GHS1000'), (2, 'GHS1100-GHS1500'), (3, 'GHS1600-GHS2000'), (4, 'GHS2100-GHS2500'), (5, 'GHS2600-GHS3000'), (6, '3000 & above')], default=1),
        ),
    ]
