# Generated by Django 5.0.3 on 2025-08-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
    ]
