# Generated by Django 4.1.7 on 2023-06-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='school',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='school',
        ),
        migrations.DeleteModel(
            name='HostelImages',
        ),
    ]
