# Generated by Django 4.1.7 on 2023-05-01 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_remove_hostel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='category',
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='Default city', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default=None, upload_to='static/apartment_images'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='cost_per_room',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='no_of_rooms',
            field=models.PositiveIntegerField(),
        ),
    ]
