# Generated by Django 4.1.7 on 2023-06-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_delete_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelimages',
            options={'verbose_name': 'Hostel Images'},
        ),
    ]
