# Generated by Django 4.1.7 on 2023-04-04 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_school_alter_hostel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostels.school'),
            preserve_default=False,
        ),
    ]
