# Generated by Django 5.2.5 on 2025-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_hostel_latitude_alter_hostel_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
    ]
