# Generated by Django 5.2.5 on 2025-08-18 05:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_hostel_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hostels/'),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hostels/gallery/'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='room_types/main/'),
        ),
        migrations.AlterField(
            model_name='roomtypeimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='room_types/gallery/'),
        ),
    ]
