# Generated by Django 4.1.7 on 2023-06-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_remove_room_hostel_remove_room_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='full_cost',
            new_name='cost_per_head',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cost_per_head',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_capacity',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_capacity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
