# Generated by Django 4.1.7 on 2023-05-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_remove_booking_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='momo_no',
            new_name='mobile_money_number',
        ),
    ]
