# Generated by Django 4.1.7 on 2023-04-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostel_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='campus',
            field=models.CharField(default='main campus', max_length=100),
        ),
    ]
