# Generated by Django 4.1.7 on 2023-06-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_alter_hostelimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelimages',
            options={'verbose_name_plural': 'Hostel Images'},
        ),
    ]
