# Generated by Django 5.2.5 on 2025-08-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_alter_hostel_latitude_alter_hostel_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='phone_number',
            field=models.CharField(max_length=60),
        ),
    ]
