# Generated by Django 4.2.6 on 2023-10-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0003_alter_room_room_occupant_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amenity", models.CharField(max_length=100)),
                (
                    "fontawesome_icon",
                    models.CharField(default="fa fa-check", max_length=100),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hostel",
            name="amenities",
            field=models.ManyToManyField(to="hostels.amenities"),
        ),
    ]
