# Generated by Django 4.1.7 on 2023-05-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_rename_momo_no_booking_mobile_money_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='message',
            new_name='city_or_town',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='mobile_money_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='digital_address',
            field=models.CharField(default=125545, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='email_address',
            field=models.EmailField(default='tsaatum@outlook.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='tim', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='saatum', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='region_of_residence',
            field=models.CharField(default='UW', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='university_identification_number',
            field=models.PositiveIntegerField(default=19024665),
            preserve_default=False,
        ),
    ]
