# Generated by Django 4.1.7 on 2023-05-29 05:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_alter_hostel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='duration',
            new_name='duration_of_rent',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+233 589 693 6595', max_length=128, region=None),
        ),
    ]
