# Generated by Django 4.1.7 on 2023-05-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.AddField(
            model_name='hostel',
            name='amenities',
            field=models.CharField(choices=[('wifi', 'wifi'), ('water', 'water'), ('kitchen', 'kitchen'), ('study area', 'study area'), ('power supply', 'power supply'), ('air condition', 'air condition')], default='wifi', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
