# Generated by Django 4.1.7 on 2023-04-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_school_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='campus',
        ),
        migrations.AddField(
            model_name='hostel',
            name='campus',
            field=models.CharField(default='Main Campus', max_length=100),
        ),
    ]
