# Generated by Django 4.1.7 on 2023-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_delete_apartment_hostel_amenities_delete_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='amenities',
            field=models.BooleanField(choices=[('wifi', 'wifi'), ('water', 'water'), ('kitchen', 'kitchen'), ('study area', 'study area'), ('power supply', 'power supply'), ('air condition', 'air condition')], default=False),
        ),
    ]
