# Generated by Django 4.1.7 on 2023-04-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_remove_school_campus_hostel_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gps_coordinates',
            field=models.CharField(default='9.8824, -0.88788', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(default='un-named hostel', max_length=50),
        ),
    ]
