# Generated by Django 4.1.7 on 2023-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_hostel_amenties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='amenties',
        ),
        migrations.AddField(
            model_name='hostel',
            name='amenities',
            field=models.CharField(default='Wifi', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HostelAmenities',
        ),
    ]
