# Generated by Django 4.1.7 on 2023-04-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_school_gps_coordinates_alter_hostel_hostel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='gps_address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='gps_coordinates',
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
