# Generated by Django 4.1.7 on 2023-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_alter_hostel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='amenities',
            field=models.CharField(choices=[('wifi', 'wifi'), ('water', 'water'), ('kitchen', 'kitchen'), ('study area', 'study area'), ('power supply', 'power supply'), ('air condition', 'air condition')], max_length=20),
        ),
    ]
