# Generated by Django 4.1.7 on 2023-05-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_remove_hostel_amenties_hostel_amenities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='amenities',
            new_name='hostel_amenities',
        ),
    ]
