# Generated by Django 4.1.7 on 2023-05-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_rename_amenities_hostel_hostel_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='ac_fan',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='bath_rooms',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='power_supply',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='study_area',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='toilet',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='water',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='wifi',
        ),
    ]
