# Generated by Django 4.1.7 on 2023-05-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_remove_hostel_ac_fan_remove_hostel_bath_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='wifi',
            field=models.CharField(default='Wifi', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostel',
            name='campus',
            field=models.CharField(default='Main Campus', help_text='Enter campus the hostel is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='cost_per_room',
            field=models.DecimalField(decimal_places=2, help_text='4500', max_digits=8),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='details',
            field=models.TextField(help_text='Enter anything that is not in the amenities'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='duration_of_rent',
            field=models.PositiveIntegerField(help_text='2'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_coordinates',
            field=models.CharField(help_text='latitude, longitude', max_length=100),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='no_of_rooms',
            field=models.PositiveIntegerField(help_text='E.g 20'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='owner_name',
            field=models.CharField(default='unarcom', help_text='Enter name of hostel owner', max_length=100),
        ),
    ]
