# Generated by Django 4.1.7 on 2023-05-31 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostels', '0009_hostel_wifi_alter_hostel_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
