# Generated by Django 4.1.7 on 2023-05-31 16:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0010_hostel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Enter anything that is not in the amenities'),
        ),
    ]
