"""
Django settings for hostelier project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
CLOUDINARY_URL = config('CLOUDINARY_URL', default='')
# print(f"CLOUDINARY_URL: {CLOUDINARY_URL}")
ENVIRONMENT = config('ENVIRONMENT', default='development')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG_STATUS', cast=bool)

ALLOWED_HOSTS = config('CURRENT_ALLOWED_HOST', cast = Csv())

# Application definition

INSTALLED_APPS = [
    'django_ckeditor_5',
    'hostels',
    'cloudinary',
    # 'cloudinary_storage',
    'crispy_bootstrap5',
    'users',
    "crispy_forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

CKEDITOR_UPLOAD_PATH = 'static/images/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'hostelier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CKEDITOR_UPLOAD_PATH = "uploads/"
# Path where uploaded images will be stored
CKEDITOR_5_FILE_STORAGE = "media/"

# CKEditor 5 configurations
CUSTOM_CONFIG = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "link", "bulletedList", "numberedList", "|",
            "blockQuote", "insertTable", "mediaEmbed", "undo", "redo"
        ],
        "height": "300px",
        "width": "100%",
    },
    "advanced": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "link", "underline", "strikethrough", "subscript", "superscript",
            "bulletedList", "numberedList", "outdent", "indent", "|",
            "blockQuote", "insertTable", "imageUpload", "mediaEmbed", "|",
            "undo", "redo", "codeBlock"
        ],
        "height": "500px",
        "width": "100%",
    }
}
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
CKEDITOR_5_CONFIGS = CUSTOM_CONFIG

WSGI_APPLICATION = 'hostelier.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
if ENVIRONMENT == 'development':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
if ENVIRONMENT == 'production':
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ.get('DATABASE_URL', 'postgresql://neondb_owner:npg_iaUm0yvEq8wB@ep-restless-butterfly-ae0djgm5-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require'),
            conn_max_age=600,
            ssl_require=True
        )
    }

INTERNAL_IPS = [
    '127.0.0.1',
]
CLOUDINARY_STORAGE = {
    'CLOUD_NAME':  config('CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
    'FOLDER': 'hostel_images',
}
# Static & Media storage
# STATICFILES_STORAGE = "cloudinary_storage.storage.StaticCloudinaryStorage"
# DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'rooms$Hostels',
#        'USER': 'rooms',
#        'PASSWORD': config('DB_PASS'),
#        'HOST': 'rooms.mysql.pythonanywhere-services.com',
#        'OPTIONS': {
#            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#        },
#    }
#}

#SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
#pwa binaries

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap5'


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_USER')
EMAIL_HOST_PASSWORD = 'kscnzqcdtpmewpxz'
AUTH_USER_MODEL = 'users.RoomUser'

PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')

#sms backends
SMS_BACKEND = 'sms.backends.twilio.SmsBackend'
TWILIO_ACCOUNT_SID = 'live-redacted-twilio-account-sid'
TWILIO_AUTH_TOKEN = 'live-redacted-twilio-auth-token'


#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARD_PROTO', 'https')
#SECURE_SSL_REDIRECT = True
#https://smsc.hubtel.com
#https://api-otp.hubtel.com
